### ISSUE TITLE
Grouping and Calculations

### ISSUE THREAD

**Issue by thiagoc7** [edelpero/lupa#3]
Hi, thanks for this fantastic gem!
I'm using `query services`, or something like this, for a long time, and with lupa it's much more organised.

Do you plan to add same methods for defaults `group`, `sum`, etc?
I think that it could help to DRY even more our controllers.

Cheers!

**Comment by edelpero** [comment]
Hi @thiagoc7, I'm glad you found useful Lupa.
I didn't understand your question. Could you please add an example of the issue?
I think that an example will clarify this for me.

Cheers

**Comment by avilaroman** [comment]
Grande! Eze!
te puse una estrella ;)
voy a probarla y te digo que onda...
mi gema es Tucubi
<https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB4QFjAA&url=https%3A%2F%2Frubygems.org%2Fgems%2Ftucubit%2Fversions%2F0.1.2&ei=5-cuVZ3ZLLDdsATXnoCwBQ&usg=AFQjCNHzEuNTtM4Yb2FpEjgQNBXrqUhbpQ&sig2=LzXpTEMYOphS_S1Nu5qr-w&bvm=bv.91071109,d.cWc>t
perteneciente a tucubit.com


mi PGP:
https://pgp.mit.edu/pks/lookup?search=avilaroman&op=index
Román Avila

**Comment by thiagoc7** [comment]
Sorry for my poor english. Take a look:

``` ruby
# app/searches/product_search.rb

class ProductSearch < Lupa::Search
  class Scope
      ...
  end

  class Calculations
    def avg_price
      scope.group(:category).average(:price)
    end
  end
end

avg_category_price = ProductSearch.new(Product.all).search(category: [10, 11, 12]).avg_price
```

**Comment by edelpero** [comment]
Hi @thiagoc7,

You should be able to achieve the same result as following:

``` ruby
# app/searches/product_search.rb

class ProductSearch < Lupa::Search
  class Scope
    def category
      ...
    end

    def avg_price
      scope.group(:category).average(:price)
    end
  end
end

products = ProductSearch.new(Product.all).search(category: [10, 11, 12], avg_price: true)
```

Every key of the search params that has a value different from nil, an empty string, an empty hash or an empty array and match a method on ProductSearch::Scope class, will trigger your the corresponding method on ProductSearch::Scope.

Please let me know if that worked for you.

**Comment by thiagoc7** [comment]
Hi @edelpero, thanks for your response.
I don't like this solution, because the order of the chain matters, at least with RoR.
`Product.sum(:price).where(category: 1)` does not work, and I think that creating this kind of methods inside `Scope` class could lead to issues in the future.

But I could achieve the result I need, see:

``` ruby
# app/searches/product_search.rb

class ProductSearch < Lupa::Search
  class Scope
      ...
  end

  def avg_price
    self.group(:category).average(:price)
  end
end

product_search = ProductSearch.new(Product.all).search(category: [10, 11, 12])
products = product_search.results
avg_category_price = product_search.avg_price
```

Do you see any problem with this solution?

**Comment by edelpero** [comment]
Oh, now I'm following what you're trying to do.

So about your first question, the answer is no. That is not what I designed Lupa for. A solution for what you're trying to achieve is:

``` ruby
# app/models/product.rb

class Product < ActiveRecord::Base
  def self.avg_price
    group(:category).average(:price)
  end
end
```

``` ruby
# app/searchs/product_search.rb

class ProductSearch < Lupa::Search
  class Scope
    ...
  end
end
```

``` ruby
avg_category_price = ProductSearch.new(Product.all).search(category: [10, 11, 12]).avg_price
```

Any other method than **scope**, **search_attributes**, *\* default_search_attributes*\* and **results** applied after the **search(...)**, will result in calling **results** method and applying that method to the resulting scope.

In this case your ProductSearch class search will return a Product::ActiveRecord_Relation class, so you can apply the **avg_price** method defined on your Product model.

I'm closing the issue now since your question is answered.

Cheers.
