### ISSUE TITLE
when no search params is receiver, it should behave like if it was not used

### ISSUE THREAD

**Issue by pywebdesign** [edelpero/lupa#5]
Hi,

Thank you for your amazing gem, I think it would be good to have 

```
UsersSearch.new(User).search(permitted_filters)
```

be equivalent to 

```
User.all
```

when `permitted_filters` is empty

what do you think?

**Comment by edelpero** [comment]
Hi @pywebdesign,

I don't like the idea of adding logic to handle an specific type of class and a particular case, since Lupa tries to be ORM agnostic, meaning that your User class could be any kind of object.

Anyway, thanks for the suggestion.
